### ISSUE TITLE
preal rule sizing breaks ACT's ability to map cells

### ISSUE THREAD

**Issue by nbingham1** [asyncvlsi/actflow#2]
**Steps to Reproduce**
```
$ touch cells.act
$ interact -ref=1 -Tsky130
interact> source interact.conf
WARNING: new cells generated; please update your cell library.
(Use ckt:cell-save to see the new cells.) New cell names are:
   g0n_0x0
interact> quit
$ interact -ref=1 -Tsky130
interact> source interact.conf
WARNING: new cells generated; please update your cell library.
(Use ckt:cell-save to see the new cells.) New cell names are:
   g0n_0x1
interact> quit
```

**test.act**
```
defproc testbench(bool a, b)
{
	preal n1 = 6.0;

	prs
	{
		a<n1> -> b-
		~a<n1> -> b+
	}
}

bool a, b;
testbench dut(a, b);
```

**interact.conf**
```
act:read "test.act"
act:merge "cells.act"
act:expand
act:top testbench
ckt:cell-map
ckt:map
ckt:cell-save "cells.act"
ckt:save-sp "cells.spi"
phydb:init
```

**Expected behavior**
interact is able to recognize same cells

**Suspected Reason**
The cell looks to be saved with integer sizing parameters whereas it was originally generated with real sizing parameters.
```
export defcell g0n_0x0 (bool? in[1]; bool! out)
{
   prs {
   in[0]<6> -> out-
   ~in[0]<6> -> out+
   }
}
```

**Versions**
Most recent commit actflow (6ba25cfd1c457c5d78d5b3b22e7e0991454922c5)
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by rmanohar** [comment]
Thanks! Reproduced and (I think) fixed. Just pushed.

**Comment by nbingham1** [comment]
I pulled the update and rebuilt and the problem persisted, I'm going to try again from a clean build and check in after that.

**Comment by nbingham1** [comment]
Yep, I can verify that this has been fixed. Thank you!
